services:

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    # ports:
    # - 4444:4444
    networks:
      - dockernet

  app:
    build: app/
    volumes:
      - ./app:/home/app
    # ports:
    # - 4444:4444
    depends_on:
      - selenium
    command: python3 src/Test.py
    networks:
    - dockernet
    restart: unless-stopped


networks:
  dockernet:
    name: dockernet
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1


  # nginx:
  #   image: nginx
  #   ports:
  #   - 8080:80
  #   volumes:
  #   - ./app/static/html:/usr/share/nginx/html
  #   restart: always

  # redis:
  #   image: redis
  #   ports:
  #   - 6379:6379