services:

  nginx:
    image: nginx
    ports:
    - 8080:80
    volumes:
    - ./app/static/html:/usr/share/nginx/html
    restart: always

  redis:
    image: redis
    ports:
    - 6379:6379

  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444